### ISSUE TITLE
build with python3

### ISSUE THREAD

**Issue by rezso** [shlomif/pysol-sound-server#1]
https://gist.github.com/rezso/e6afe7b27ea090fbaf5007ca68b8bd45

**Comment by shlomif** [comment]
Regarding the first problem, you can do `make PYTHON=python3`. The other problems will be harder to fix.

**Comment by shlomif** [comment]
@rezso : please try commit 3b3315884f73d49a48546c91e302cf57800e321c - it seems to work fine in py3.

**Comment by rezso** [comment]
Yes, it works. Thank you. I think, you can release it.

**Comment by shlomif** [comment]
On Tue, 20 Mar 2018 21:19:02 +0000 (UTC)
rezso <notifications@github.com> wrote:

> Yes, it works. Thank you. I think, you can release it.
> 

thanks! I have set up a git tag for 3.10 .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/ways_to_do_it.html

If a million Shakespeares had to write together, they would write like a monkey.
    — based on Stephen Wright, via Nadav Har’El.

Please reply to list if it's a mailing list post - http://shlom.in/reply .
